musicworld/urls.py
from django.conf.urls import patterns, url
from musicworld import views

#set urls to show specific page
urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^article/$', views.article, name='article'),
    url(r'^article/create/$', views.create_article, name='create_article'),
    url(r'^(?P<article_id>\d+)/$', views.detail, name='detail'),
    url(r'^article/(?P<article_id>\d+)/$', views.adetail, name='adetail'),
    url(r'^login/$',views.login,name = 'login'),
    url(r'^user/$',views.user,name = 'user'),
    url(r'^regist/$',views.regist,name = 'regist'),
    url(r'^index/$',views.index,name = 'index'),
    url(r'^logout/$',views.logout,name = 'logout'),
    url(r'^(?P<article_id>\d+)/createcomment/$', views.create, name='create'),
    url(r'^article/like/(?P<article_id>\d+)/$', views.like_article, name='like_article'),
    url(r'^likep/(?P<periodical_id>\d+)/$', views.like_periodical, name='like_periodical'),
    url(r'^periodical/$', views.phome, name='phome'),
    url(r'^periodical/(?P<periodical_id>\d+)/$', views.pdetail, name='pdetail'),
    url(r'^video/$', views.video, name='video'),
    url(r'^contact/$', views.contact, name='contact'),
    
    url(r'^(?P<periodical_id>\d+)/createpcomment/$', views.pcreate, name='pcreate'),
)

mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

#urls that start with musicworld and admin
#url admin is linked to page to manage at backend
#url musicworld and revelant urls linked to show page
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite5.views.home', name='home'),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^musicworld/', include('musicworld.urls', namespace="musicworld")),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_PATH, 'show_indexes':True}),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musicworld/models.py
from django.db import models

from django.contrib import admin
# Create your models here.
#class of user
class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.username


#list user in admin to show username and password
class UserAdmin(admin.ModelAdmin):
    list_display = ('username','password')

#class of article and properties of it
class Article(models.Model):
    #__table__ = 'articles'

    name = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    music = models.FileField('article-music',upload_to='music/article')
    content = models.TextField(max_length=1000)
    articleimage = models.FileField('article-image',upload_to='image/article')
    timestamp = models.DateTimeField(auto_now=True)
    likes = models.IntegerField(default=0)

    
    def __str__(self):
        return self.name

#list article in admin to show name and timastamp
class ArticleAdmin(admin.ModelAdmin):
    list_display = ('name','timestamp')


#class of comment and properties of it
#set article as a foreignkey to it
class Comment(models.Model):
    #__table__ = 'acomment'

    timestamp = models.DateTimeField(auto_now=True)
    content = models.TextField(max_length=1000)
    article = models.ForeignKey(Article)


    def __str__(self):
        return self.content

#class type pf periodical
class Ptype(models.Model):
    #__table__ = 'Ptype'

    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

#class of periodical and properties of it
#set ptype as a foreignkey to it
class Periodical(models.Model):
    #__table__ = 'periodicals'

    name = models.CharField(max_length=200)
    ptype = models.ForeignKey(Ptype)
    content = models.TextField(max_length=1000)
    image = models.FileField('periodical-image',upload_to='image/periodical')
    timestamp = models.DateTimeField(auto_now=True)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.name


#class of periodical's comment and properties of it
#set periodical as a foreignkey to it
class Pcomment(models.Model):
    #__table__ = 'acomment'

    timestamp = models.DateTimeField(auto_now=True)
    content = models.TextField(max_length=1000)
    periodical = models.ForeignKey(Periodical)


    def __str__(self):
        return self.content

#class of music and properties of it
#set article as a foreignkey to it
class Music(models.Model):
    #__table__ = 'musics'

    name = models.CharField('music-title',max_length=200)
    artist = models.CharField('music-artist',max_length=200)
    album = models.CharField('music-album',max_length=200)
    musicimage = models.FileField('music-image',upload_to='image/musics',max_length=100)
    timestamp = models.DateTimeField(auto_now=True)
    periodical = models.ForeignKey(Periodical)
    music = models.FileField('musicM',upload_to='music/musics')
    
    def __str__(self):
        return self.name


#class of userinformation and properties of it
class Userinformation(models.Model):
    #__table__ = 'users'

    email = models.CharField(max_length=200,null=True)
    hobby = models.CharField(max_length=200,null=True)
    image = models.FileField('user-image',upload_to='/image/userinformation',null=True)
    user = models.OneToOneField(User)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.hobby

musicworld/views.py
from django.shortcuts import get_object_or_404,render

# Create your views here.
from django.shortcuts import render,render_to_response
from django.http import HttpResponse,HttpResponseRedirect

from django.core.urlresolvers import reverse
from django.template import RequestContext, loader

from django import forms
from django.forms import ModelForm 
from django.core.context_processors import csrf

from musicworld.models import User
from musicworld.models import Article
from musicworld.models import Comment
from musicworld.models import Periodical
from musicworld.models import Pcomment
from musicworld.models import Userinformation
from musicworld.models import Ptype
#form
class UserForm(forms.Form): 
    username = forms.CharField(label='Username',max_length=100)
    password = forms.CharField(label='Password',widget=forms.PasswordInput())

#homepage(befor login)
def home(request):
    latest_article_list = Article.objects.order_by('-id')[:5]
    username = request.COOKIES.get('username','')
    context = {'latest_article_list': latest_article_list,'username':username}
    return render(request, 'articles.html', context)


def detail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    comments = Comment.objects.filter(article_id=article.id)
    return render(request, 'singlearticle.html', {'article': article,'comments': comments})


#show article
def article(request):
    latest_article_list = Article.objects.order_by('-id')[:5]
    recommend= Article.objects.order_by('-likes')[:5]
    username = request.COOKIES.get('username','')
    context = {'latest_article_list': latest_article_list,'username':username,'recommend':recommend}
    return render(request, 'articles.html', context)


def adetail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    comments = Comment.objects.filter(article_id=article.id)
    return render(request, 'singlearticle.html', {'article': article,'comments': comments})

#regist
def regist(req):
    if req.method == 'POST':
        uf = UserForm(req.POST)
        if uf.is_valid():
            #get date of form
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            #add into database
            User.objects.create(username= username,password=password)
            response = HttpResponseRedirect('/musicworld/index/')
            response.set_cookie('username',username,3600)
            return response
    else:
        uf = UserForm()
    return render_to_response('regist.html',{'uf':uf}, context_instance=RequestContext(req))

#login
def login(req):
    if req.method == 'POST':
        uf = UserForm(req.POST)
        if uf.is_valid():
            #get data
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            #compare with the database
            user = User.objects.filter(username__exact = username,password__exact = password)
            if user:
                #match,go into index
                response = HttpResponseRedirect('/musicworld/index/')
                #set cookie
                response.set_cookie('username',username,3600)
                return response
            else:
                #doesnt match,still login page
                return HttpResponseRedirect('/musicworld/login/')
    else:
        uf = UserForm()
    return render_to_response('login.html',{'uf':uf},context_instance=RequestContext(req))

#login success
def index(req):
    username = req.COOKIES.get('username','')
    latest_periodical_list = Periodical.objects.order_by('-timestamp')[:3]
    a=latest_periodical_list[0]
    b=latest_periodical_list[1]
    c=latest_periodical_list[2]
    latest_article_list = Article.objects.order_by('-timestamp')[:3]
    d = Article.objects.order_by('-likes')[:1]
    return render_to_response('index.html' ,{'username':username,'latest_article_list':latest_article_list,'a':a,'b':b,'c':c,'d':d})

#logout
def logout(req):
    response = HttpResponse('logout !!')
    #delete cookie
    response.delete_cookie('username')
    return response


#create comment
class CommentForm(forms.ModelForm):    
    class Meta:  
        model = Comment 
        fields = ['content']



def create(request,article_id):
    a = Article.objects.get(id=article_id)

    if request.method == "POST":
        form = CommentForm(request.POST) 
        
        if form.is_valid():

            c = form.save(commit=False)
            c.article = a
            c.save()


            return HttpResponseRedirect('/musicworld/%s' % article_id)
    else:
        form = CommentForm()

    args = {}
    args.update(csrf(request))

    args['article'] = a
    args['form'] = form

    return render_to_response('create_comment.html',args)

#add likes
def like_article(request,article_id):
	if article_id:
		a = Article.objects.get(id=article_id)
		count = a.likes
		count += 1
		a.likes = count
		a.save()
	return HttpResponseRedirect('/musicworld/article/%s' % article_id)

#add likes periodical
def like_periodical(request,periodical_id):
    if periodical_id:
        a = Periodical.objects.get(id=periodical_id)
        count = a.likes
        count += 1
        a.likes = count
        a.save()
    return HttpResponseRedirect('/musicworld/periodical/%s' % periodical_id)  	


#show peridical
def phome(request):
    latest_periodical_list = Periodical.objects.order_by('-timestamp')[:5]
    popularp = Periodical.objects.order_by('-likes')[:5]
    username = request.COOKIES.get('username','')
    context = {'latest_periodical_list': latest_periodical_list,'username':username,'popularp': popularp}
    return render(request, 'periodical.html', context)

def pdetail(request, periodical_id):
    periodical = get_object_or_404(Periodical, pk=periodical_id)
    pcomments = Pcomment.objects.filter(periodical_id=periodical.id)
    return render(request, 'singleperiodical.html', {'periodical': periodical,'pcomments': pcomments})


#create article
class ArticleForm(forms.ModelForm):    
    class Meta:  
        model = Article 
        fields = ['name','content','articleimage','music']


def create_article(request):
    
    if request.method == "POST":
        
        form = ArticleForm(request.POST, request.FILES)
        username = request.COOKIES.get('username','')
        
        if form.is_valid():
            
            form.articleimage = Article(articleimage = request.FILES['articleimage'])
            form.music = Article(music = request.FILES['music'])
            form.author = username
            form.save()

            return HttpResponseRedirect('/musicworld/article')
    else:
        form = ArticleForm()

    args = {}
    args.update(csrf(request))

    args['form'] = form

    return render_to_response('create_article.html',args)



def video(request):
    return render(request, 'video.html')

def user(request):

    info = Userinformation.objects.order_by('-timestamp')[:1]
    return render(request, 'user.html', {'info': info})

def contact(request):
    return render(request, 'contact.html')


#create pcomment
class PcommentForm(forms.ModelForm):    
    class Meta:  
        model = Pcomment 
        fields = ['content']


def pcreate(request,periodical_id):
    a = Periodical.objects.get(id=periodical_id)

    if request.method == "POST":
        form = PcommentForm(request.POST) 
        
        if form.is_valid():

            c = form.save(commit=False)
            c.periodical = a
            c.save()


            return HttpResponseRedirect('/musicworld/periodical/%s' % periodical_id)
    else:
        form = PcommentForm()

    args = {}
    args.update(csrf(request))

    args['periodical'] = a
    args['form'] = form

    return render_to_response('create_pcomment.html',args)

musicworld/templates/articles.html

<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta property="qc:admins" content="4553322067645776654" />
	<meta name="baidu-site-verification" content="xC1m9aYTgX" />
	<title>MusicWorld</title> 
	
	<link rel="stylesheet" href="/static/css/essay.css">

</head>
<body>
		
	<!-- header start -->
	<div class="header">
		<div class="header-ct">
			<a href="/musicworld/index" class="logo">
				<img src="http://4.bp.blogspot.com/-RSW7GpwPaP4/TZFMVLjAyBI/AAAAAAAAAAo/6lFZFqTm0lQ/s45/music-notes.jpg">
			</a>
			<div class="nav">
				<ul class="clearfix">
					<li><a href="/musicworld/periodical">Periodicals</a></li>
					<li><a href="/musicworld/article/">Articles</a></li>
					<li><a href="/musicworld/video/">Videos</a></li>
					<li><a href="/musicworld/contact/">Contact</a></li>			

				</ul>

			</div>
			
				<div class="head-search">
					<form class="search-form" action="/" id="headSearchForm">
						<input type="text" class="search-input" name="q" autocomplete="off">
						<button class="search-btn" type="submit">
							<span class="icon-search"></span>
						</button>
					</form>
				</div>			<!-- logged-in-wrapper -->
			<div>
<div class="logged-out-wrapper">



<script type="text/javascript"> 
function displaySubMenu(li) { 
var subMenu = li.getElementsByTagName("ul")[0]; 
subMenu.style.display = "block"; 
} 
function hideSubMenu(li) { 
var subMenu = li.getElementsByTagName("ul")[0]; 
subMenu.style.display = "none"; 
} 
</script> 
</head> 
<body> 
<ul id="navigation"> 
<li onMouseOver="displaySubMenu(this)" onMouseOut="hideSubMenu(this)"> 
<a href="#">Welcome,{{username}}!</a> 
<ul> 
<li><a href="/musicworld/user">Edit Profile</a></li> 
<li><a href="/musicworld/login">Sign out</a></li> 
</ul>        
</div>
 </a>		
</div>
</div>

			
	</div>
	<!--/// header end -->
	<!-- container start -->
	<div class="container">	

		<div class="clearfix">

			<!-- article start-->
			<div class="article article-sm">

				<!-- essay-list -->
				<div class="essay-list">
				





							{% if latest_article_list %}
								<ul>
    						{% for article in latest_article_list %}
    						<p>{{article.likes}} people like this article</p>
    						
							<div class="item">
								<a href="" class="cover-wrapper">
									<img class="cover rounded" src="/media/{{ article.articleimage}}" alt="">
								</a>
								<div class="essay-wrapper rounded">									
									<li><a href="{% url 'musicworld:adetail' article.id %}">
										{{ article.name}}
									</a>
									<div class="meta">
										<span class="category">Posted</span><span class="separator">&#12539;</span><a class="entry-author" >{{article.author}}</a><span class="separator">&#12539;</span><span class="time">{{ article.timestamp}}</span>
									</div>
									<div class="subscribe">
										{{ article.content}}
									</div>
								</div>
							</div>
							{% endfor %}
   								 </ul>
							{% else %}
    						<p>No polls are available.</p>
						{% endif %}
							
							
				</div>
				<!--/// essay-list end-->

				<div class="paginator">
					<a class="previous disabled" rel="nofollow" href="javascript:;">Previous</a><a class="page actived" rel="nofollow" href="javascript:;">1</a><a class="page">2</a><a class="page" >3</a><a class="page" >4</a><a class="page">5</a><a class="page" >6</a><a class="page" >7</a><a class="page" >8</a><a class="page">9</a><a class="page" >10</a><span class="break">...</span><a class="page">25</a><a class="next">Next</a>				</div>
			</div>
			<!--/// article end-->

			<!-- aside start-->
			<div class="aside">
				
				<div class="widget">
					<div class="widget-head">						
						<span class="title">Recommend</span>				
					</div>

					<div class="widget-ct pic-widget">
					{% if recommend %}
					{% for recommend in recommend %}
						<div class="item">
							<a href="{% url 'musicworld:adetail' recommend.id %}" title="" class="cover-wrapper">
								<img src="/media/{{recommend.articleimage}}" alt="" class="cover rounded">
							</a>
							<div class="info">
								<a href="{% url 'musicworld:adetail' recommend.id %}" title="" class="title">{{recommend.name}}</a>
								<p class="description"><span>Liked</span><span class="separator">&#12539;</span>{{recommend.likes}} people</p>
							</div>
						</div>
					{% endfor %}	
					{% endif %}					
					</div>
				</div>

				<div class="widget">
					<div class="widget-ct">
						<a href="/musicworld/article/create" class="ln-widget-block rounded">
							Upload Your Article
						</a>
					</div>
				</div>

							</div>
			<!--/// aside end-->

		</div>
	</div>
	<!--/// container end -->
<script type="text/javascript">
$(function(){
	$('.aside')
	.stick_in_parent({offset_top: 15})
	.on("sticky_kit:bottom", function(e) {
		//console.log( $(this) );
		$(this).css({top: 0, bottom: '', position: 'fixed'})
	});
})
</script>

<div class="footer">
	<div class="foot-ct clearfix">
		<div class="about-wrapper">
			<h3 class="foot-item-head">created by group b</h3>
			
		</div>
	</div>
</div>



</body>
</html>

musicworld/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
</head>
<body>

	<!--content-->
	{% block content %}
	
	{% endblock %}
	<!--end content-->

</body>
<html>

musicworld/templates/contact.html

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta property="qc:admins" content="4553322067645776654" />
    <meta name="baidu-site-verification" content="xC1m9aYTgX" />
    <title>Music</title> 
    <link rel="stylesheet" href="/static/css/index.css">
    <link rel="stylesheet" href="/static/css/layout.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link type="image/x-icon" href="http://www.luoo.net/favicon.ico" rel="shortcut icon">   
    <script src="http://s.luoo.net/thirdparty/jquery/jquery-1.11.0.min.js?v2.3.1"></script>
    
        <script src="http://s.luoo.net/js/luoo.js?v2.3.1"></script>
            <script>
        if( $.luoo.browser()['ie'] && $.luoo.browser()['version'] < 8 )
        {
            window.location.href = 'http://www.luoo.net/browser_not_supported/';
        }
    </script>
</head>
<body>
        
    <!-- header start -->
    <div class="header">
        <div class="header-ct">
            <a href="/musicworld/" class="logo">
                <img src="http://4.bp.blogspot.com/-RSW7GpwPaP4/TZFMVLjAyBI/AAAAAAAAAAo/6lFZFqTm0lQ/s45/music-notes.jpg">
            </a>
            <div class="nav">
                <ul class="clearfix">
                  <li><a href="/musicworld/periodical">Periodicals</a></li>
                    <li><a href="/musicworld/article/">Articles</a></li>
                    <li><a href="/musicworld/video/">Videos</a></li>
                    <li><a href="#">Contact</a></li>          

                </ul>

            </div>
            
                <div class="head-search">
                    <form class="search-form" action="http://www.luoo.net/search/" id="headSearchForm">
                        <input type="text" class="search-input" name="q" autocomplete="off">
                        <button class="search-btn" type="submit">
                            <span class="icon-search"></span>
                        </button>
                    </form>
                </div>          <!-- logged-in-wrapper -->
            <div>


    <div class="col-2">
        <h2>Contact Us</h2>
        <form action="" id="form1">
           
                <label>Your Name:<input type="text"></label>
                <label>Your E-mail:<input type="email"></label>
                <label>Your City:<input type="text"></label>
                <label class="msg">Your Message:<textarea></textarea></label>
                <div class="btns"><a href="javascript:document.getElementById('form1').reset()" class="more">Clear</a><input type="button" class="more" onClick="send()" value="send"></a></div>
          
        </form>
    </div>
<script type="text/javascript">
function send(){
    a= document.getElementById('form1');
    if(a==0)
        alert("Please fill in the form");
location.href="#";
else
    alert("Information sent successfully!");
location.href="/musicworld/index";
 }
</script>
    
    <!--/// header end -->  

        
        <!--/// section end -->
        
                


                                                                        
    <!--/// container end -->

</body>
</html>

musicworld/templates/index.html

<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta property="qc:admins" content="4553322067645776654" />
	<meta name="baidu-site-verification" content="xC1m9aYTgX" />
	<title>Music</title> 
	<link rel="stylesheet" href="/static/css/index.css">
	<link type="image/x-icon" href="http://www.luoo.net/favicon.ico" rel="shortcut icon">	
	<script src="http://s.luoo.net/thirdparty/jquery/jquery-1.11.0.min.js?v2.3.1"></script>
	
		<script src="http://s.luoo.net/js/luoo.js?v2.3.1"></script>
			<script>
	    if( $.luoo.browser()['ie'] && $.luoo.browser()['version'] < 8 )
	    {
	    	window.location.href = 'http://www.luoo.net/browser_not_supported/';
	    }
	</script>

<style>
body { 
font-family:verdana, sans-serif; 
font-size:small; 
} 

#navigation, #navigation li ul { 
list-style-type:none; 
} 
#navigation { 

 position: absolute;
    right: 15px;
    top: 5px;
} 
#navigation li { 
float:left; 
text-align:center; 
position:relative; 
} 
#navigation li a:link, #navigation li a:visited { 
display:block; 
text-decoration:none; 
color:#000; 
width:120px; 
height:40px; 
line-height:40px; 
border:1px solid #fff; 
border-width:0px 0px 0 0; 
background:transparent; 
padding-left:10px; 
} 
#navigation li a:hover { 
color:#fff; 
background:#2687eb; 
} 
#navigation li ul li a:hover { 
color:#fff; 
background:#6b839c; 
} 
#navigation li ul { 
display:none; 
position:absolute; 
top:40px; 
left:0; 
margin-top:1px; 
width:120px; 
} 
#navigation li ul li ul { 
display:none; 
position:absolute; 
top:0px; 
left:130px; 
margin-top:0; 
margin-left:1px; 
width:120px; 
} 
</style>
</head>


<body>
		
	<!-- header start -->
	<div class="header">
		<div class="header-ct">
			<a href="/musicworld/index" class="logo">
				<img src="http://4.bp.blogspot.com/-RSW7GpwPaP4/TZFMVLjAyBI/AAAAAAAAAAo/6lFZFqTm0lQ/s45/music-notes.jpg">
			</a>
			<div class="nav">
				<ul class="clearfix">
					<li><a href="/musicworld/periodical">Periodicals</a></li>
					<li><a href="/musicworld/article">Articles</a></li>
					<li><a href="/musicworld/video">Videos</a></li>
					<li><a href="/musicworld/contact">Contact</a></li>			

				</ul>

			</div>
			
				<div class="head-search">
					<form class="search-form" action="http://www.luoo.net/search/" id="headSearchForm">
						<input type="text" class="search-input" name="q" autocomplete="off">
						<button class="search-btn" type="submit">
							<span class="icon-search"></span>
						</button>
					</form>
				</div>			<!-- logged-in-wrapper -->
			<div>
<div class="logged-out-wrapper">



<script type="text/javascript"> 
function displaySubMenu(li) { 
var subMenu = li.getElementsByTagName("ul")[0]; 
subMenu.style.display = "block"; 
} 
function hideSubMenu(li) { 
var subMenu = li.getElementsByTagName("ul")[0]; 
subMenu.style.display = "none"; 
} 
</script> 
</head> 
 <body>
<ul id="navigation"> 
<li onMouseOver="displaySubMenu(this)" onMouseOut="hideSubMenu(this)"> 
<a href="#">Welcome,{{username}}!</a> 
<ul> 
<li><a href="/musicworld/user">Edit Profile</a></li> 
<li><a href="/musicworld/login">Sign out</a></li> 
</ul>         
</div>
 </a>		
</div>
</div>

			
	</div>
	
	<!--/// header end -->	<!-- container start -->
	<div class="container index-ct">	
		
			
		<div class="section-vol">
			<div class="section-head clearfix">
				<h3><span class="section-head-label"></span>Periodical</h3>
				
			</div>
		
			<div class="section-ct clearfix">
				{% if a %}
				<div class="vol-item-lg">
					<a href="{% url 'musicworld:pdetail' a.id %}" class="cover-wrapper cover-wrapper-lg">
						<img src="/media/{{a.image}}"  class="cover-lg rounded">
						<span class="icon-play-lg"></span>
						<div class="play-btn-mask"></div>
					</a>

					<a href="{% url 'musicworld:pdetail' a.id %}" class="title">vol.{{a.name}}</a>
				</div>
				{% endif %}
				{% if b %}
					<div class="vol-item">
						<a href="{% url 'musicworld:pdetail' b.id %}" class="cover-wrapper">
							<img src="/media/{{b.image}}"  class="cover rounded">
							<span class="icon-play"></span>
							<div class="play-btn-mask"></div>
						</a>

						<a class="title" href="{% url 'musicworld:pdetail' b.id %}">vol.{{b.name}}</a>
					</div>
				{% endif %}	
				{% if c %}	
					<div class="vol-item">
						<a href="{% url 'musicworld:pdetail' c.id %}" class="cover-wrapper">
							<img src="/media/{{c.image}}"  class="cover rounded">
							<span class="icon-play"></span>
							<div class="play-btn-mask"></div>
						</a>

						<a class="title" href="{% url 'musicworld:pdetail' c.id %}">vol.{{c.name}}</a>
					</div>
				{% endif %}
								</div>
		</div>
		<!--/// section end -->
		
				

		<div class="section-m clearfix">
			<div class="section-musician">
				<div class="section-head clearfix">
					<h3><span class="section-head-label"></span>Original Recommendation</h3>
				</div>
				{% if d %}
				<div class="section-ct">
					<div class="clearfix">
						<img src="http://images.sodahead.com/polls/000426079/polls_int_music_1703_560352_answer_1_xlarge.jpeg" class="cover rounded">
						<div class="title">
							<div class="align-fix">
								<div>
									<a href="" class="single-name">Music</a>
									<p class="artist">LC</p>
									<p class="pubdate">2014-01-04</p>
								</div>
							</div>
							
						</div>
					</div>
					<div class="remark">
						<span class="quote-before"></span> <span>For years I’ve been raving about my great fiery love for this band to pretty much anyone who would listen, and so to see them enjoy such success this year has been a thing of enormous joy for me. I’m not sure they sit so neatly in the Americana bracket, but they’re from Baltimore and I adore them, so I’m claiming them as my own. This of course is the single, and the Letterman performance, that first turned heads back in March. Much has been made of Samuel T Herring as frontman – the bullish frame, the dancing, the ferocity, but behind the impeccable showmanship there lies something incredibly special – music that is heartfelt and guttural and true.</span> <span class="quote-after"></span> 
					</div>
				</div>
				{% endif %}
			</div>
			<!-- /// section-musician end -->

			<div class="section-essay">
				<div class="section-head clearfix">		
				</div>
				<div class="section-ct clearfix">
					    {% if latest_article_list %}
					    {% for article in latest_article_list %}
						<div class="essay-item">
							<a href="{% url 'musicworld:adetail' article.id %}" class="cover-wrapper">
								<img src="/media/{{article.articleimage}}" class="cover rounded">
							</a>
							<div class="meta rounded">
								<p class="title"><a class="ln-title" href="{% url 'musicworld:adetail' article.id %}" title="The Beatles">{{article.name}}</a></p>
								<p class="author">Posted by:{{article.author}}</p>
								<p class="author">Posted on:{{article.timestamp}}</p>
							</div>
						</div>
						{% endfor %}
						{% endif %}
						
										</div>
			</div>
		</div>
		<!-- /// section end -->
			

		
			<div class="section-head clearfix">
				<h3><span class="section-head-label"></span>Hot Video</h3>
			</div>




<div >
<iframe class="movie1" width="460" height="315" src="http://www.youtube.com/embed/QHxzs6YEqk8" frameborder="0" allowfullscreen></iframe></div>
<div>
<iframe class="movie1_relative" width="460" height="315" src="http://www.youtube.com/embed/bESGLojNYSo" frameborder="0" allowfullscreen></iframe>
</div>	
	

																		
	<!--/// container end -->
<div class="footer">
		<div id="footer-inner">
			<span class="alignleft">&copy; <a href="http://workingstorage.com/">www.music.com</a>. </span>
			<span class="alignright">
				 Powered by Music
				&nbsp;|&nbsp;
				Website Designed by Group B		</span>
			<div class="clearfix"></div>
		</div><!-- #footer-inner -->
	</div><!-- #footer -->
</body>
</html>